using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using ReservEase.Alumni.Common.Sdk.Extensions;
using ReservEase.Alumni.Common.Sdk.Models;
using ReservEase.Alumni.PostgresDb.Sdk.Entities;
using ReservEase.Alumni.PostgresDb.Sdk.Models;
using ReservEase.Alumni.Reports.Sdk.Models;
using ReservEase.Alumni.Reports.Sdk.Services;

namespace ReservEase.Alumni.Platform.Api.Controllers;

/// <summary>
/// Downloadable reports for platform staff. Requested here, generated by Operations.Worker
/// (GenerateReportWorkflow), downloaded here. Which reports a staff member may run is decided per
/// report by role (see ReportCatalog), so the controller itself only requires a signed-in staff account.
/// </summary>
[Authorize]
public class ReportsController(IReportJobService reportJobs) : DefaultController
{
    private ReportRequester Requester()
    {
        var staff = User.GetAccount();
        return new ReportRequester(
            ReportAudiences.Platform, InstitutionId: null, staff.Id, staff.Name, staff.Email, staff.Role,
            IsScoped: false, YearGroups: [], CommunityIds: [], DisabledFeatures: []);
    }

    [HttpGet("catalog")]
    [SwaggerOperation(Summary = "Reports this staff member can request")]
    [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ApiResponse<IReadOnlyList<ReportDefinitionDto>>))]
    public IActionResult GetCatalog() =>
        reportJobs.GetAvailable(Requester()).ToOkApiResponse().ToActionResult();

    [HttpPost("jobs")]
    [SwaggerOperation(Summary = "Request a report", Description = "Queues the report and returns at once. The requester is notified in-app and by email when it is ready to download")]
    [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(ApiResponse<ReportJobDto>))]
    [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(ApiResponse<object>))]
    public async Task<IActionResult> RequestReport([FromBody] RequestReportRequest request)
    {
        var result = await reportJobs.RequestAsync(Requester(), request);
        return result.ToActionResult();
    }

    [HttpGet("jobs")]
    [SwaggerOperation(Summary = "My requested reports", Description = "The signed-in staff member's own reports, newest first, with their status")]
    [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ApiResponse<PgPagedResult<ReportJobDto>>))]
    public async Task<IActionResult> GetReportJobs([FromQuery] int page = 1, [FromQuery] int pageSize = 20)
    {
        var result = await reportJobs.ListAsync(Requester(), page, pageSize);
        return result.ToActionResult();
    }

    [HttpGet("jobs/{id}/download")]
    [SwaggerOperation(Summary = "Download a finished report", Description = "Only the staff member who requested it, and only until it expires")]
    [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(ApiResponse<object>))]
    public async Task<IActionResult> DownloadReport(string id)
    {
        var download = await reportJobs.OpenDownloadAsync(Requester(), id);
        if (download is null)
            return ApiResponseExtensions.ToNotFoundApiResponse<object>("This report isn't available to download. It may have expired; request it again.").ToActionResult();
        return File(download.Content, download.ContentType, download.FileName);
    }
}
