<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReservEase.Alumni.Common.Sdk\ReservEase.Alumni.Common.Sdk.csproj" />
    <ProjectReference Include="..\ReservEase.Alumni.PostgresDb.Sdk\ReservEase.Alumni.PostgresDb.Sdk.csproj" />
    <ProjectReference Include="..\ReservEase.Alumni.Storage.Sdk\ReservEase.Alumni.Storage.Sdk.csproj" />
    <ProjectReference Include="..\ReservEase.Alumni.Temporal.Sdk\ReservEase.Alumni.Temporal.Sdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Temporalio" Version="1.*" />
  </ItemGroup>

</Project>
