<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../src/ReservEase.Alumni.Platform.Api/ReservEase.Alumni.Platform.Api.csproj" />
    <ProjectReference Include="../../src/ReservEase.Alumni.PostgresDb.Sdk/ReservEase.Alumni.PostgresDb.Sdk.csproj" />
    <ProjectReference Include="../../src/ReservEase.Alumni.Common.Sdk/ReservEase.Alumni.Common.Sdk.csproj" />
    <ProjectReference Include="../../src/ReservEase.Alumni.Redis.Sdk/ReservEase.Alumni.Redis.Sdk.csproj" />
    <ProjectReference Include="../../src/ReservEase.Alumni.Mailtrap.Sdk/ReservEase.Alumni.Mailtrap.Sdk.csproj" />
    <ProjectReference Include="../../src/ReservEase.Alumni.Temporal.Sdk/ReservEase.Alumni.Temporal.Sdk.csproj" />
  </ItemGroup>

</Project>
