namespace ReservEase.Alumni.PostgresDb.Sdk.Entities;

public static class ReportJobStatuses
{
    public const string Queued = "Queued";
    public const string Running = "Running";
    public const string Ready = "Ready";
    public const string Failed = "Failed";
    /// <summary>The file has been deleted after its retention period. The row stays as a record that the report was run.</summary>
    public const string Expired = "Expired";
}

public static class ReportAudiences
{
    public const string Institution = "Institution";
    public const string Platform = "Platform";
}

/// <summary>
/// One requested report: what was asked for, by whom, and where the finished file is.
/// Requested through an API, generated by Operations.Worker's GenerateReportWorkflow, and
/// downloaded through the API again — the file itself is stored privately and has no URL.
///
/// Not ITenantScoped: platform staff request reports too, and those belong to no institution.
/// Every read therefore filters on <see cref="RequestedById"/> explicitly (see ReportJobService) —
/// a report is only ever visible to the person who asked for it, because its contents were cut
/// to that person's permissions when it ran.
/// </summary>
public class ReportJob : BaseEntity
{
    /// <summary>See <see cref="ReportAudiences"/>.</summary>
    public string Audience { get; set; } = ReportAudiences.Institution;
    /// <summary>Null for a platform report.</summary>
    public string? InstitutionId { get; set; }

    public string RequestedById { get; set; } = string.Empty;
    public string RequestedByName { get; set; } = string.Empty;
    public string RequestedByEmail { get; set; } = string.Empty;

    /// <summary>
    /// The requester's data scope, frozen when they asked. The worker has no signed-in user to consult,
    /// and a report must not widen if the requester's role changes between asking and generation.
    /// False + empty lists for a platform report, where scope doesn't apply.
    /// </summary>
    public bool RequesterIsScoped { get; set; }
    public List<int> ScopeYearGroups { get; set; } = [];
    public List<string> ScopeCommunityIds { get; set; } = [];

    /// <summary>A key from ReportCatalog, e.g. "members".</summary>
    public string ReportType { get; set; } = string.Empty;
    /// <summary>The catalog title at the time of the request, so the history still reads right if a report is later renamed.</summary>
    public string Title { get; set; } = string.Empty;
    /// <summary>"xlsx" or "csv".</summary>
    public string Format { get; set; } = "xlsx";
    /// <summary>Filters the requester chose (date range, status…), keyed by ReportParameters names.</summary>
    public Dictionary<string, string> Parameters { get; set; } = [];

    /// <summary>See <see cref="ReportJobStatuses"/>.</summary>
    public string Status { get; set; } = ReportJobStatuses.Queued;
    public DateTime? StartedAt { get; set; }
    public DateTime? CompletedAt { get; set; }
    /// <summary>When the file is deleted. Set once the report is ready.</summary>
    public DateTime? ExpiresAt { get; set; }

    public int RowCount { get; set; }
    /// <summary>Private storage key of the finished file. Null until ready, and again once expired.</summary>
    public string? FileKey { get; set; }
    public string? FileName { get; set; }
    public long FileSizeBytes { get; set; }
    /// <summary>A sentence fit to show the requester. The technical detail is in the worker's logs.</summary>
    public string? FailureReason { get; set; }
}
