using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using ReservEase.Alumni.Institution.Api.Services.Interfaces;
using ReservEase.Alumni.Common.Sdk.Extensions;
using ReservEase.Alumni.Common.Sdk.Models;
using ReservEase.Alumni.Institution.Api.Extensions;
using ReservEase.Alumni.Institution.Api.Models;
using ReservEase.Alumni.PostgresDb.Sdk.Entities;
using ReservEase.Alumni.PostgresDb.Sdk.Models;
using ReservEase.Alumni.Reports.Sdk.Models;
using ReservEase.Alumni.Reports.Sdk.Services;

namespace ReservEase.Alumni.Institution.Api.Controllers;

[Authorize(Roles = "SuperAdmin,ScopedAdmin")]
public class ReportsController(
    IReportService reportService,
    IAnalyticsService analyticsService,
    IReportJobService reportJobs
) : DefaultController
{
    [HttpGet("summary")]
    [SwaggerOperation(Summary = "Get reports summary metrics")]
    [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ApiResponse<ReportSummaryDto>))]
    public async Task<IActionResult> GetReportSummary()
    {
        var admin = User.GetAccount();
        var result = await reportService.GetReportSummaryAsync(admin);
        return result.ToActionResult();
    }

    [HttpGet("revenue-trend")]
    [SwaggerOperation(Summary = "Paid revenue by month and source", Description = "The latest N calendar months (default 6) of successful payments, for the dashboard chart. Full history is on the Reports page.")]
    [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ApiResponse<RevenueTrendDto>))]
    public async Task<IActionResult> GetRevenueTrend([FromQuery] int months = 6)
    {
        var admin = User.GetAccount();
        var result = await reportService.GetRevenueTrendAsync(admin, months);
        return result.ToActionResult();
    }

    [HttpGet("analytics")]
    [SwaggerOperation(Summary = "Analytics", Description = "Growth, participation, dues standing, money, member make-up and recent activity, cut to the admin's scope and to the features that are switched on")]
    [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ApiResponse<InstitutionAnalyticsDto>))]
    public async Task<IActionResult> GetAnalytics()
    {
        var institution = HttpContext.Items["Institution"] as PostgresDb.Sdk.Entities.Institution;
        var result = await analyticsService.GetAnalyticsAsync(User.GetAccount(), institution?.DisabledFeatures ?? []);
        return result.ToActionResult();
    }

    // ── Downloadable reports ────────────────────────────────────────────────
    // Requested here, generated by Operations.Worker (GenerateReportWorkflow), downloaded here.
    // Nothing below builds a file inside the request.

    private ReportRequester Requester()
    {
        var admin = User.GetAccount();
        var institution = HttpContext.Items["Institution"] as PostgresDb.Sdk.Entities.Institution;
        return new ReportRequester(
            ReportAudiences.Institution, institution?.Id, admin.Id, admin.Name, admin.Email, admin.Role,
            IsScoped: admin.Role == StaffRoles.ScopedAdmin,
            YearGroups: admin.YearGroups ?? [], CommunityIds: admin.CommunityIds ?? [],
            DisabledFeatures: institution?.DisabledFeatures ?? []);
    }

    [HttpGet("catalog")]
    [SwaggerOperation(Summary = "Reports this admin can request", Description = "Leaves out reports for switched-off features and, for a scoped admin, reports that can't be cut to their scope")]
    [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ApiResponse<IReadOnlyList<ReportDefinitionDto>>))]
    public IActionResult GetCatalog() =>
        reportJobs.GetAvailable(Requester()).ToOkApiResponse().ToActionResult();

    [HttpPost("jobs")]
    [SwaggerOperation(Summary = "Request a report", Description = "Queues the report and returns at once. The requester is notified in-app and by email when it is ready to download")]
    [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(ApiResponse<ReportJobDto>))]
    [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(ApiResponse<object>))]
    public async Task<IActionResult> RequestReport([FromBody] RequestReportRequest request)
    {
        var result = await reportJobs.RequestAsync(Requester(), request);
        return result.ToActionResult();
    }

    [HttpGet("jobs")]
    [SwaggerOperation(Summary = "My requested reports", Description = "The signed-in admin's own reports, newest first, with their status")]
    [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ApiResponse<PgPagedResult<ReportJobDto>>))]
    public async Task<IActionResult> GetReportJobs([FromQuery] int page = 1, [FromQuery] int pageSize = 20)
    {
        var result = await reportJobs.ListAsync(Requester(), page, pageSize);
        return result.ToActionResult();
    }

    [HttpGet("jobs/{id}/download")]
    [SwaggerOperation(Summary = "Download a finished report", Description = "Only the admin who requested it")]
    [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(ApiResponse<object>))]
    public async Task<IActionResult> DownloadReport(string id)
    {
        ReportDownload? download;
        try
        {
            download = await reportJobs.OpenDownloadAsync(Requester(), id);
        }
        catch (ReportFileMissingException)
        {
            return ApiResponseExtensions.ToNotFoundApiResponse<object>("This report's file can't be found in storage. Please request the report again.").ToActionResult();
        }
        catch (ReportFileUnavailableException e)
        {
            return ApiResponseExtensions.ToServerErrorApiResponse<object>($"{e.Message} Please try again in a few minutes.").ToActionResult();
        }
        if (download is null)
            return ApiResponseExtensions.ToNotFoundApiResponse<object>("We couldn't find that report.").ToActionResult();
        return File(download.Content, download.ContentType, download.FileName);
    }
}
