<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../src/ReservEase.Alumni.Institution.Api/ReservEase.Alumni.Institution.Api.csproj" />
    <ProjectReference Include="..\..\src\ReservEase.Alumni.Member.Api\ReservEase.Alumni.Member.Api.csproj" />
    <ProjectReference Include="..\..\src\ReservEase.Alumni.Platform.Api\ReservEase.Alumni.Platform.Api.csproj" />
    <ProjectReference Include="..\..\src\ReservEase.Alumni.PaymentCallbacks.Sdk\ReservEase.Alumni.PaymentCallbacks.Sdk.csproj" />
    <ProjectReference Include="..\..\src\ReservEase.Alumni.Operations.Worker\ReservEase.Alumni.Operations.Worker.csproj" />
  </ItemGroup>

</Project>
